config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations=> "users/registrations" }
  
  scope "(:locale)", :locale => /en|de|ar/ do
    resources :uploads
    resources :projects
    resources :cities
    resources :categories
    resources :event_occurrences
    root to: 'cities#index'
    resources :events
    post 'uploads/upload', to: 'uploads#upload'
    get 'projects/:id/participate', to: 'projects#participate'
    get 'projects/:id/find_participants', to: 'projects#find_participants'
    get 'projects/:id/invite/:participant_id', to: 'projects#invite'
    get 'projects/:id/approve/:participant_id', to: 'projects#approve'
    get 'projects/:id/decline/:participant_id', to: 'projects#decline'
    get 'projects/:id/:participant_id/accept', to: 'projects#accept_invite'
    get 'cities/:id/participate', to: 'cities#participate'
  
    get 'cities/:id/invite/:invitationHash', to: 'cities#invite'
    get 'event_occurrences/:id/attend', to: 'event_occurrences#attend'
    get 'event_occurrences/:id/decline', to: 'event_occurrences#decline'
    get 'my/event_occurrences', to: 'event_occurrences#mine'
    
    resources :users
  end
end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id              :integer          not null, primary key
#  title           :string
#  description     :text
#  city_id         :integer
#  category_id     :integer
#  time            :datetime
#  urgent          :boolean
#  required_people :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  is_private      :boolean
#

class Project < ActiveRecord::Base
  acts_as_taggable_on :skills, :language_skills, :studies, :working_experiences
  attr_accessor :new_skill, :new_language_skill, :new_study, :new_working_experience

  has_many :users, -> { distinct }, :through => :users_projects
  has_many :users_projects
  has_many :events
  has_many :uploads
  has_many :participants, :through => :participations, :class_name => 'User'
  has_many :participations

  belongs_to :city
  belongs_to :category
  validates :category, :presence => true
  validates :title, :presence => true
  validates :city, :presence => true

  accepts_nested_attributes_for :users, :users_projects, :participants, :participations

  def has_view_permission?(user)
    if !is_private || (!user.nil? && (participations.where(:status => 0).collect{ | part | part.participant }.include?(user) || user.try(:admin?)))
      return true
    else
      return false
    end
  end

  def has_edit_permission?(user)
    if !user.nil? && (users.include?(user) || user.try(:admin?))
      return true
    else
      return false
    end
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy, :participate, :approve, :decline, :find_participants, :invite, :accept_invite]
  before_action :authenticate_user!, only: [:participate]

  def index
    @projects = policy_scope(Project.all)
    @cities = City.all
    @categories = Category.where(category: nil)
  end

  def show
    authorize @project, :show?
  end

  def new
    @project = Project.new(:city => City.find(params[:city_id]))
    authorize @project, :new?
  end

  def edit
    authorize @project, :edit?
  end

  def create
    @project = Project.new(project_params)
    authorize @project, :create?
	if params[:project].has_key?(:new_skill) && params[:project][:new_skill] != nil && params[:project][:new_skill] != ""
      params[:project][:skill_list] << params[:project][:new_skill]
    end

    if params[:project].has_key?(:new_language_skill) && params[:project][:new_language_skill] != nil && params[:project][:new_language_skill] != ""
      params[:project][:language_skill_list] << params[:project][:new_language_skill]
    end

    if params[:project].has_key?(:new_working_experience) && params[:project][:new_working_experience] != nil && params[:project][:new_working_experience] != ""
      params[:project][:working_experience_list] << params[:project][:new_working_experience]
    end

    if params[:project].has_key?(:new_study) && params[:project][:new_study] != nil && params[:project][:new_study] != ""
      params[:project][:study_list] << params[:project][:new_study]
    end
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    authorize @project, :update?
	if params[:project].has_key?(:new_skill) && params[:project][:new_skill] != nil && params[:project][:new_skill] != ""
      params[:project][:skill_list] << params[:project][:new_skill]
    end

    if params[:project].has_key?(:new_language_skill) && params[:project][:new_language_skill] != nil && params[:project][:new_language_skill] != ""
      params[:project][:language_skill_list] << params[:project][:new_language_skill]
    end

    if params[:project].has_key?(:new_working_experience) && params[:project][:new_working_experience] != nil && params[:project][:new_working_experience] != ""
      params[:project][:working_experience_list] << params[:project][:new_working_experience]
    end

    if params[:project].has_key?(:new_study) && params[:project][:new_study] != nil && params[:project][:new_study] != ""
      params[:project][:study_list] << params[:project][:new_study]
    end
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @project, :destroy?

    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def participate
    authorize @project, :participate?

    @participation = Participation.where(:project => @project, :participant => current_user).first_or_create

    if @project.is_private
      @participation.status=:applied
      UserMailer.participation_request_email(current_user, @participant, @project).deliver
    else
      @participation.status=:approved
    end

    respond_to do |format|
      if @participation.save
        format.html { redirect_to @project, notice: 'Successfully applied.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def accept_invite
    authorize @project, :participate?

    @participation = Participation.where(:project => @project, :participant => User.find(params[:participant_id])).first_or_create

    @participation.status=:approved

    respond_to do |format|
      if @participation.save
        format.html { redirect_to @project, notice: 'Successfully applied.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def find_participants
    authorize @project, :find_participants?

    @users = CityParticipation.where(:city => @project.city).map{|e| e.participant}.flatten
    @users.delete_if{|user| user.projects.exists?(@project) || user == current_user}
    @users.sort{|a, b| b.common_tags(@project) <=> a.common_tags(@project)}
  end

  def approve
    authorize @project, :approve?

    participation = Participation.find(params[:participant_id])

    respond_to do |format|
      if participation.update(:status => :approved)
        format.html { redirect_to @project, notice: 'Participant was successfully approved.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def invite
    authorize @project, :invite?
    @participant = User.find(params[:participant_id])
    
    @participation = Participation.where(:project => @project, :participant => @participant).first_or_create
    @participation.generate_token
    @participation.status=:invited
    
    
    UserMailer.invitation_email(@participant, @project, current_user, "/#{I18n.locale}/projects/#{@project.id}/#{@participant.id}/accept/#{@participation.invitationHash}").deliver
    respond_to do |format|
      if @participation.save
        format.html { redirect_to "/#{I18n.locale}/projects/#{@project.id}/find_participants", notice: t('.participant_invited') }
      else
        format.html { redirect_to "/#{I18n.locale}/projects/#{@project.id}/find_participants", error: t('.something_went_wrong') }
      end
    end
  end
  
  

  def decline
    authorize @project, :decline?

    participation = Participation.find(params[:participant_id])
    participation.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Participant was successfully declined.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :description, :city_id, :category_id, :time, { skill_list: [], study_list:[], working_experience_list:[], language_skill_list:[] }, :new_language_skill, :new_working_experience, :new_study, :new_skill, :urgent, :required_people, :is_private, :project_ids => [], :user_ids => [])
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  
  def participate_project_path(project)
    "/#{I18n.locale}/projects/#{project.id}/participate"
  end
  
  def project_accept_path(project, user)
    "/#{I18n.locale}/projects/#{project.id}/#{user.id}/accept"
  end
  
  def approve_participant_path(project, participant)
    "/#{I18n.locale}/projects/#{project.id}/approve/#{participant.id}"
  end
  
  def decline_participant_path(project, participant)
    "/#{I18n.locale}/projects/#{project.id}/decline/#{participant.id}"
  end
  
  def find_participants_project_path(project)
    "/#{I18n.locale}/projects/#{project.id}/find_participants"
  end
  
  def project_invite_user_path(project, user)
    "/#{I18n.locale}/projects/#{project.id}/invite/#{user.id}"
  end
  
end

app/views/projects/_form.html.slim
= simple_form_for(@project) do |f|
  = f.error_notification
  .form-group
    = f.label :title, class: "col-sm-2 control-label"

    .col-sm-10
      = f.input :title, :label => false, class: "form-control col-md-10"
    = f.label :description, class: "col-sm-2 control-label"

    .col-sm-10
      = f.input :description, :label => false, class: "form-control col-md-10"
    = f.label :city, class: "col-sm-2 control-label"

    .col-sm-10
      = f.association :city, :label => false, class: "form-control col-md-10"
    = f.label :category, class: "col-sm-2 control-label"

    .col-sm-10
      = f.association :category, :label => false, class: "form-control col-md-10"

    .form-group
      = f.label :language_skills, :class => "col-sm-2 control-label"

      .col-sm-10
        = f.input_field :language_skill_list, label: false, as: :check_boxes, collection: Tagging.where(:context => "language_skills").joins(:tag).select('DISTINCT tags.name').map{ |x| x.name}
        = f.label :new_language_skill
        = f.text_field "new_language_skill", class: "form-control", 'data-role': "tagsinput"

    .form-group
      = f.label :studies , :class => "col-sm-2 control-label"

      .col-sm-10
        = f.input_field :study_list, label: false, as: :check_boxes, collection: Tagging.where(:context => "studies").joins(:tag).select('DISTINCT tags.name').map{ |x| x.name}
        = f.label :new_study
        = f.text_field "new_study", class: "form-control", 'data-role': "tagsinput"

    .form-group
      = f.label :working_experience, :class => "col-sm-2 control-label"

      .col-sm-10
        = f.input_field :working_experience_list, label: false, as: :check_boxes, collection: Tagging.where(:context => "working_experiences").joins(:tag).select('DISTINCT tags.name').map{ |x| x.name}
        = f.label :new_working_experience
        = f.text_field "new_working_experience", class: "form-control", 'data-role': "tagsinput"

    .form-group
      = f.label :skills, :class => "col-sm-2 control-label"

      .col-sm-10
        = f.input_field :skill_list, label: false, as: :check_boxes, collection: Tagging.where(:context => "skills").joins(:tag).select('DISTINCT tags.name').map{ |x| x.name}
        = f.label :new_skill
        = f.text_field "new_skill", class: "form-control", 'data-role': "tagsinput"

    = f.label :urgent, class: "col-sm-2 control-label"

    .col-sm-10
      = f.input :urgent, :label => false, class: "form-control col-md-10"

    = f.label :is_private, class: "col-sm-2 control-label"

    .col-sm-10
      = f.input :is_private, :label => false, class: "form-control col-md-10"

    = f.label :users, class: "col-md-2 control-label"

    .col-md-10
      = f.association :users, :as => :check_boxes, :label => false, boolean_style: :inline, item_wrapper_tag: :div, item_wrapper_class: "col-md-3 col-md-offset-1 well"

  .form-actions
    = f.button :submit

app/views/projects/edit.html.slim
h1
  = t '.editing_1'
= render 'form'
= link_to (t '.show_5'), @project

= link_to (t '.back_9'), projects_path

app/views/projects/find_participants.html.slim
.row
  .col-md-12
    h3
      = t '.users'

    table.table.table-striped
      tbody
        - @users.each do |user|
          tr
            = render partial:"users/user_for_project", locals: {user: user, project: @project}

app/views/projects/index.html.slim
p#notice
  = notice
.row
  .col-md-3
    ul.list-group
      - @categories.each do |cat|
        li.list-group-item
          = cat.title

  .col-md-9
    h1
      = t '.listing_1'

    table.table.table-striped
      thead
        tr
          th
            = t '.title_4'
          th
            = t '.description'
          th
            = t '.city'
          th
            = t '.category_3'
          th
            = t '.time'
          th
            = t '.urgent_1'
          th
            = t '.required'
          th[colspan="3"]
      tbody
        - @projects.each do |project|
          tr
            td
              = project.title
            td
              = project.description
            td
              = project.city
            td
              = project.category
            td
              = project.time
            td
              = project.urgent
            td
              = project.required_people
            td
              = link_to (t '.show_6'), project
            td
              = link_to (t '.edit_8'), edit_project_path(project)
            td
              = link_to (t '.destroy_5'), project, method: :delete, data: { confirm: 'Are you sure?' }

    br
    = link_to (t '.new_project_2'), new_project_path

app/views/projects/new.html.slim
h1
  = t '.new_project_3'
= render 'form'
= link_to (t '.back_10'), projects_path

app/views/projects/show.html.slim
h2
  = @project.title

.row
  .col-md-12
    = raw "&nbsp;"

.row
  .col-md-3
    - if (@project.city.participants.include?(current_user) && !@project.participants.include?(current_user))
      p
        = link_to (t '.participate_1'), participate_project_path(@project), :class=> 'btn btn-default'
    - if @project.has_edit_permission?(current_user)
      p
        = link_to nl2br(t(:find_participants)), find_participants_project_path(@project), :class=> 'btn btn-default btn-info'
    - if (@project.city.participants.include?(current_user))
      p
  	    = raw "&nbsp;"
      h4
        = t '.verantwortliche'

      ul.nav.navbar-stacked
        - @project.users.each do |user|
          li
            - if user_signed_in? && @project.participants.include?(current_user)
              .media
                .media-left
                  = link_to image_tag(user.avatar.url(:thumb), :class => "media-object", :size=>"50x50"), user_url(user)
								
                .media-body
								  = link_to user.name, user_url(user)
            - else
              = user.name
			
			h4
			  = t '.files'
			- if @project.uploads.size > 0
			  table.table.table-striped
     	    thead
            tr
              th[width="100"]
              th
                = t '.files'
              - if @project.has_edit_permission?(current_user)
                th[colspan="2"]
          tbody
            - @project.uploads.each do |upload|
              tr
                td
                  - if upload.file.exists?(:thumb)
                    = link_to image_tag(upload.file.url(:thumb)), upload.file.url(:original, false)
                td
                    = link_to upload.name, upload.file.url(:original, false)
                - if @project.has_edit_permission?(current_user)
                  td
                    = link_to (t :edit), edit_upload_path(upload)
                  td
                    = link_to (t :destroy), upload, method: :delete, data: { confirm: 'Are you sure?' }

      br
      - if @project.has_edit_permission?(current_user)
        = simple_form_for(Upload.new(project_id: @project.id), {url: "/uploads/upload", html: { multipart: true, class: "dropzone"}}) do |f|
          = f.error_notification
          = f.hidden_field :project_id
          .form-inputs
          .fallback
             = f.file_field :file
             br

      br
      br
      = link_to (t '.edit_11'), edit_project_path(@project), :class=> "btn btn-default"

          

  .col-md-9
    p
      = @project.description

		- if @project.has_edit_permission?(current_user) && @project.participations.where(:status => 1).size > 0
        table.table.table-striped
          thead
            tr
              th[width="100"]
              th
                = t '.nutzer_1'
              th[colspan="2"]

          tbody
            - @project.participations.where(:status => 1).each do |participation|
              tr
                td
                  - if participation.participant.avatar.exists?(:thumb)
                    = image_tag participation.participant.avatar.url(:thumb)
                td
                  = participation.participant.name
                td
                  = link_to (t '.approve'), approve_participant_path(@project, participation)
                td
                  = link_to (t '.decline'), decline_participant_path(@project, participation)

    - if @project.has_view_permission?(current_user)
      - iterator = 0
      - @project.events.each do |ev|
        - iterator+=1
        - ev.remaining_event_occurrences.sort_by(&:urgency).reverse.each do |event|
          .panel.panel-default
            .panel-body
              - if user_signed_in?
                - if !event.users.include?(current_user)
                  = link_to (l(event.date)), attend_event_occurrence_path(event), data: { confirm: 'Teilnahme für diesen Termin anbieten?' }
                  = link_to (t(".help")), attend_event_occurrence_path(event), data: { confirm: 'Teilnahme für diesen Termin anbieten?' }, :class => "btn btn-default btn-primary btn-xs pull-right"
                - else
                  = l(event.date)
              - else
                = link_to (l(event.date)), attend_event_occurrence_path(event), data: { confirm: 'Teilnahme für diesen Termin anbieten?' }
              = raw("<br /><br />")
              = t '.von', :event => (event.remaining_free_places), :ev_required => (ev.required_people)
              - if @project.has_edit_permission?(current_user)
              
                = link_to (raw("<span class=\"glyphicon glyphicon-pencil\" aria-hidden=\"true\"></span> ")+(t :edit)), edit_event_path(ev), :class => "btn btn-default btn-xs pull-right"
                = link_to (raw("<span class=\"glyphicon glyphicon-trash\" aria-hidden=\"true\"></span> ")+(t :destroy)), ev, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-default btn-xs pull-right"


      
        
      - if @project.has_edit_permission?(current_user)
        = link_to (t '.new_event_2'), new_event_path(project_id: @project.id), :class=> "btn btn-default"
        br

      br
      
        
    = link_to (t '.back_11'), city_path(@project.city), :class=> "btn btn-default"