config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations=> "users/registrations" }
  
  scope "(:locale)", :locale => /en|de|ar/ do
    resources :uploads
    resources :projects
    resources :cities
    resources :categories
    resources :event_occurrences
    root to: 'cities#index'
    resources :events
    post 'uploads/upload', to: 'uploads#upload'
    get 'projects/:id/participate', to: 'projects#participate'
    get 'projects/:id/find_participants', to: 'projects#find_participants'
    get 'projects/:id/invite/:participant_id', to: 'projects#invite'
    get 'projects/:id/approve/:participant_id', to: 'projects#approve'
    get 'projects/:id/decline/:participant_id', to: 'projects#decline'
    get 'projects/:id/:participant_id/accept', to: 'projects#accept_invite'
    get 'cities/:id/participate', to: 'cities#participate'
  
    get 'cities/:id/invite/:invitationHash', to: 'cities#invite'
    get 'event_occurrences/:id/attend', to: 'event_occurrences#attend'
    get 'event_occurrences/:id/decline', to: 'event_occurrences#decline'
    get 'my/event_occurrences', to: 'event_occurrences#mine'
    
    resources :users
  end
end

app/models/city.rb
# == Schema Information
#
# Table name: cities
#
#  id             :integer          not null, primary key
#  title          :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  invitationHash :string
#

class City < ActiveRecord::Base
  has_many :users, -> { distinct }, :through => :users_cities
  has_many :users_cities
  has_many :projects
  has_many :participants, :through => :city_participations, :class_name => 'User'
  has_many :city_participations

  accepts_nested_attributes_for :users, :users_cities, :participants, :city_participations

  before_create :generate_token

  def generate_token
    self.invitationHash = loop do
      random_token = SecureRandom.urlsafe_base64(nil, false)
      break random_token unless self.class.exists?(invitationHash: random_token)
    end
  end

end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy, :invite, :participate]
  before_action :authenticate_user!, only: [:edit, :update, :destroy]

  # GET /cities
  # GET /cities.json
  def index
    @cities = policy_scope(City.all)

  end

  # GET /cities/1
  # GET /cities/1.json
  def show
    authorize @city, :show?
    @projects = @city.projects.order('urgent DESC, title')
    @categories = Category.where(:category => nil)
  end

  # GET /cities/new
  def new
    @city = City.new
    authorize @city, :new?
  end

  # GET /cities/1/edit
  def edit
    authorize @city, :edit?
  end

  def invite
    authorize @city, :edit?
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(city_params)
    authorize @city, :create?

    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, notice: 'City was successfully created.' }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    authorize @city, :update?
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to @city, notice: 'City was successfully updated.' }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city.destroy
    authorize @city, :destroy?

    respond_to do |format|
      format.html { redirect_to cities_url, notice: 'City was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def participate
    authorize @city, :participate?

    @participation = CityParticipation.where(:city => @city, :participant => current_user).first_or_create
    @participation.status = :approved

    respond_to do |wants|
      if @participation.save
        wants.html { redirect_to @city, notice: 'Successfully applied.' }
        wants.json { render :show, status: :created, location: @city }
      else
        wants.html { render :new }
        wants.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
   end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
      @city.generate_token unless @city.invitationHash
      @city
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def city_params
      params.require(:city).permit(:title, :user_ids => [])
    end
end

app/helpers/cities_helper.rb
module CitiesHelper
  
  def participate_city_path(city)
    "/#{I18n.locale}/cities/#{city.id}/participate"
  end
  
  def invite_city_path(city)
    "/#{I18n.locale}/cities/#{city.id}/invite/#{city.invitationHash}"
  end
  
end

app/views/cities/_categories.html.slim
- categories.each do |cat|
  li
    =link_to category_path(cat, :city_id => @city.id) do
      - depth.times
        | &nbsp;

      = cat.title
		
  - if cat.children.any?
	  = render :partial => 'categories', :locals => {:categories => cat.children, :depth => (depth+2)}

    

app/views/cities/_form.html.slim
= simple_form_for(@city, :html=> { :class=>"form-horizontal"}) do |f|
  = f.error_notification
  .form-group
    = f.label :title, class: "col-md-2 control-label"
    .col-md-10
      = f.input :title, :label => false, class: "form-control col-md-10"
    = f.label :users, class: "col-md-2 control-label"
    .col-md-10
      = f.association :users, :as => :check_boxes, :label => false, boolean_style: :inline, item_wrapper_tag: :div, item_wrapper_class: "col-md-3 col-md-offset-1 well"
  .form-actions
    = f.button :submit

app/views/cities/edit.html.slim
h1
  = t '.editing_city'
= render 'form'
= link_to (t '.show_2'), @city

= link_to (t '.back_3'), cities_path

app/views/cities/index.html.slim
h1
  = t '.herzlich'

table.table.table-striped
  thead
    tr
      th
        = t '.in_welcher'
      - if user_signed_in?
        - if current_user.try(:admin?)
          th
  tbody
    - @cities.sort.each do |city|
      tr
        td
          = link_to city.title, city
        - if user_signed_in?
          - if current_user.try(:admin?)
            td
              = link_to (raw("<span class=\"glyphicon glyphicon-pencil\" aria-hidden=\"true\"></span> ")+(t '.edit_3')), edit_city_path(city), :class => "btn btn-default btn-xs"
              = link_to (raw("<span class=\"glyphicon glyphicon-trash\" aria-hidden=\"true\"></span> ")+(t '.destroy_2')), city, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-default btn-xs"

br
- if user_signed_in?
  - if current_user.try(:admin?)
    = link_to (t '.new_city'), new_city_path, :class=> "btn btn-default"

app/views/cities/new.html.slim
h1
  = t '.new_city_1'
= render 'form'
= link_to (t '.back_4'), cities_path

app/views/cities/show.html.slim
h1
  = t('.unsere_1', city_title: @city.title)
.row
  .col-md-3
    - if (!@city.participants.include?(current_user))
      p
        = link_to (t '.participate'), participate_city_path(@city), :class=> 'btn btn-default'
    h3
      = t '.kategorien_1'
    ul.nav.navbar-stacked
      li 
        = link_to (t '.alle_1'), city_path(@city)
      = render :partial => 'categories', :locals => {:categories => @categories, :depth => 0}
    - if (@city.participants.include?(current_user))
      h4
        = t '.verantwortliche'
      ul.nav.navbar-stacked
        - @city.users.each do |user|
          li
            - if user_signed_in?
              	.media
									.media-left
									  = link_to image_tag(user.avatar.url(:thumb), :class => "media-object", :size=>"50x50"), user_url(user)

									.media-body
									  = link_to user.name, user_url(user)
            - else
              = user.name
    - if user_signed_in?
      - if current_user.try(:admin?) || @city.users.include?(current_user)

  .col-md-9
    table.table.table-striped
      thead
        tr
          th
            = t '.title_2'
          th
            = t '.category_1'
          - if user_signed_in?
            - if current_user.try(:admin?)
              th[colspan="2"]
      tbody
        - @projects.each do |project|
          - if project.urgent == true
            tr.danger
          -else
            tr

          td
            = link_to project.title, project
          td
            = link_to project.category.title, project
          - if user_signed_in?
            - if current_user.try(:admin?)
              td
                = link_to (raw("<span class=\"glyphicon glyphicon-pencil\" aria-hidden=\"true\"></span> ")+(t '.edit_4')), edit_project_path(project)
              td
                = link_to (raw("<span class=\"glyphicon glyphicon-trash\" aria-hidden=\"true\"></span> ")+(t '.destroy_3')), project, method: :delete, data: { confirm: 'Are you sure?' }
    br
    - if user_signed_in?
      - if current_user.try(:admin?) || @city.users.include?(@current_user)
        = link_to (t '.new_project_1'), new_project_path(city_id: @city.id), :class=> "btn btn-default"

= link_to (t '.back_5'), cities_path