config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations=> "users/registrations" }
  
  scope "(:locale)", :locale => /en|de|ar/ do
    resources :uploads
    resources :projects
    resources :cities
    resources :categories
    resources :event_occurrences
    root to: 'cities#index'
    resources :events
    post 'uploads/upload', to: 'uploads#upload'
    get 'projects/:id/participate', to: 'projects#participate'
    get 'projects/:id/find_participants', to: 'projects#find_participants'
    get 'projects/:id/invite/:participant_id', to: 'projects#invite'
    get 'projects/:id/approve/:participant_id', to: 'projects#approve'
    get 'projects/:id/decline/:participant_id', to: 'projects#decline'
    get 'projects/:id/:participant_id/accept', to: 'projects#accept_invite'
    get 'cities/:id/participate', to: 'cities#participate'
  
    get 'cities/:id/invite/:invitationHash', to: 'cities#invite'
    get 'event_occurrences/:id/attend', to: 'event_occurrences#attend'
    get 'event_occurrences/:id/decline', to: 'event_occurrences#decline'
    get 'my/event_occurrences', to: 'event_occurrences#mine'
    
    resources :users
  end
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id          :integer          not null, primary key
#  title       :string
#  category_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Category < ActiveRecord::Base
  has_many :children, :dependent => :destroy, :class_name => 'Category'

  belongs_to :category
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :destroy]

  def index
    @categories = policy_scope(Category.all)
  end

  def show
    authorize @category, :show?
    @city = City.find(params[:city_id])
    @categories = Category.where(:category => nil)
    @projects = Project.where(:category => @category, :city => @city)
  end

  def new
    @category = Category.new
    authorize @category, :new?
  end

  def edit
    authorize @category, :edit?
  end

  def create
    @category = Category.new(category_params)
    authorize @category, :create?

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    authorize @category, :update?

    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_path, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @category, :destroy?

    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:title, :category_id)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_categories.html.slim
ul.list-group
  - categories.each do |cat|
    li.list-group-item
      - if cat.children.any?
        h4
          =link_to cat.title, category_path(cat, :city_id => @city.id)
        = render :partial => 'categories', :locals => {:categories => cat.children}
      - else
        =link_to cat.title, category_path(cat, :city_id => @city.id)

app/views/categories/_form.html.slim
= simple_form_for(@category) do |f|
  = f.error_notification
  .form-inputs
    = f.input :title
    = f.association :category
  .form-actions
    = f.button :submit

app/views/categories/edit.html.slim
h1
  = t '.editing'
= render 'form'
= link_to (t '.show'), @category
= link_to (t '.back'), categories_path

app/views/categories/index.html.slim
h1
  = t '.listing'
table.table.table-striped
  thead
    tr
      th
        = t '.title'
      - if user_signed_in?
        - if current_user.try(:admin?)
          th
  tbody
    - @categories.each do |category|
      tr       
        td
          = link_to category.title, category
        - if user_signed_in?
          - if current_user.try(:admin?)
			td
				= link_to (raw("<span class=\"glyphicon glyphicon-pencil\" aria-hidden=\"true\"></span> ")+(t '.edit')), edit_category_path(category), :class => "btn btn-default btn-xs"
				= link_to (raw("<span class=\"glyphicon glyphicon-trash\" aria-hidden=\"true\"></span> ")+(t '.destroy')), category, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-default btn-xs"
br
= link_to (t '.new_category'), new_category_path

app/views/categories/new.html.slim
h1
  = t '.new_category_1'
= render 'form'
= link_to (t '.back_1'), categories_path

app/views/categories/show.html.slim
h1
  = t '.unsere', :city_title => (@city.title)
  small
    = @category.title

.row
  .col-md-3
    h3
      = t '.kategorien'
    = link_to (t '.alle'), city_path(@city)
    = render :partial => 'categories', :locals => {:categories => @categories}
  .col-md-9
    table.table.table-striped
      thead
        tr
          th
            = t '.title_1'
          th
            = t '.category'
          - if user_signed_in?
            - if current_user.try(:admin?)
              th[colspan="2"]
      tbody
        - @projects.each do |project|
          - if project.urgent == true
            tr.danger
          - else
            tr

          td
            = link_to project.title, project
          td
            = link_to project.category.title, project

          - if user_signed_in?
            - if current_user.try(:admin?)
              td
                = link_to (t '.edit_1'), edit_project_path(project)
              td
                = link_to (t '.destroy_1'), project, method: :delete, data: { confirm: 'Are you sure?' }

    br
    - if user_signed_in?
      - if current_user.try(:admin?)
        = link_to (t '.new_project'), new_project_path(city_id: @city.id)

- if user_signed_in?
  - if current_user.try(:admin?)
    = link_to (t '.edit_2'), edit_city_path(@city)
    |  |


= link_to (t '.back_2'), cities_path