config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations=> "users/registrations" }
  
  scope "(:locale)", :locale => /en|de|ar/ do
    resources :uploads
    resources :projects
    resources :cities
    resources :categories
    resources :event_occurrences
    root to: 'cities#index'
    resources :events
    post 'uploads/upload', to: 'uploads#upload'
    get 'projects/:id/participate', to: 'projects#participate'
    get 'projects/:id/find_participants', to: 'projects#find_participants'
    get 'projects/:id/invite/:participant_id', to: 'projects#invite'
    get 'projects/:id/approve/:participant_id', to: 'projects#approve'
    get 'projects/:id/decline/:participant_id', to: 'projects#decline'
    get 'projects/:id/:participant_id/accept', to: 'projects#accept_invite'
    get 'cities/:id/participate', to: 'cities#participate'
  
    get 'cities/:id/invite/:invitationHash', to: 'cities#invite'
    get 'event_occurrences/:id/attend', to: 'event_occurrences#attend'
    get 'event_occurrences/:id/decline', to: 'event_occurrences#decline'
    get 'my/event_occurrences', to: 'event_occurrences#mine'
    
    resources :users
  end
end

app/views/layouts/_messages.html.slim
- # Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    -if name.to_s == 'notice' ? 'success' : 'danger'
      .alert.alert-success
        = content_tag :div, :id => "flash_#{name}" do
          = msg
          button.close[type="button" data-dismiss="alert" aria-hidden="true"] x
    -else
      .alert.alert-danger
        = content_tag :div, :id => "flash_#{name}" do
          = msg
          button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×

    

app/views/layouts/_navigation.html.slim
- # navigation styled for Bootstrap 3.0
nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only
          = t '.toggle'
        span.icon-bar
        span.icon-bar
        span.icon-bar

      = link_to (t '.home'), root_path, class: 'navbar-brand'

    .collapse.navbar-collapse
      ul.nav.navbar-nav
        = render 'layouts/navigation_links'

      ul.nav.navbar-nav.navbar-right
		- if I18n.locale.to_s != 'en'
		  li
			= link_to image_tag("country_flags/United-kingdom-flag.png", height: '20'), url_for( :locale => 'en' )
		
		- if I18n.locale.to_s != 'de'
		  li
			= link_to image_tag("country_flags/Germany-flag.png", height: '20'), url_for( :locale => 'de' )

		- if I18n.locale.to_s != 'ar'
		  li
			= link_to image_tag("country_flags/Syria-flag.png", height: '20'), url_for( :locale => 'ar' )

        - if user_signed_in?
          li
            = link_to t(:edit_account), edit_user_registration_path
          li
            = link_to t(:sign_out), destroy_user_session_path, :method=>'delete'
        - else
          li
            = link_to t(:sign_in), new_user_session_path
          li
            = link_to t(:sign_up), new_user_registration_path

app/views/layouts/_navigation_links.html.slim
- # add navigation links to this file
li
  = link_to t(:cities_overview), cities_path

- if user_signed_in?
  li
    = link_to t(:my_events), my_events_path
  - if current_user.try(:admin?)
	li
      = link_to t(:categories_overview), categories_path
    li
      = link_to t(:users_overview), users_path

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : "Deutschland hilft"
    |  <meta name="description" content="
    = content_for?(:description) ? yield(:description) : "Rails Devise"
    | ">
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    header
      = render 'layouts/navigation'
    main[role="main"]
      br
      br
      .container
        ol.breadcrumb
          = t '.sie_sind_hier'
          li
            = link_to t(:cities_overview), cities_path()

          - if (@city && @city.id != nil) || (@project && @project.id != nil) || (@event && @event.id != nil)
            li
              - if @city
                = link_to @city.title, city_path(@city)
              - elsif @project
                = link_to @project.city.title, city_path(@project.city)
              - elsif @event.is_a? Event
                = link_to @event.project.city.title, city_path(@event.project.city)
              - elsif @event.is_a? EventOccurrence
                = link_to @event.event.project.city.title, city_path(@event.event.project.city)

            - if (@project && @project.id != nil) || (@event && @event.id != nil)
              li
                - if @project
                  = link_to @project.title, project_path(@project)
                - elsif @event.is_a? Event
                  = link_to @event.project.title, project_path(@event.project)
                - elsif @event.is_a? EventOccurrence
                  = link_to @event.event.project.title, project_path(@event.event.project)


        = render 'layouts/messages'
        = yield